/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CarRouteAddDTO,
  CarRouteRequestResponse,
  CarRouteUpdateDTO,
  RequestResponse,
} from '../models';
import {
    CarRouteAddDTOFromJSON,
    CarRouteAddDTOToJSON,
    CarRouteRequestResponseFromJSON,
    CarRouteRequestResponseToJSON,
    CarRouteUpdateDTOFromJSON,
    CarRouteUpdateDTOToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models';

export interface ApiCarRouteAddPostRequest {
    carRouteAddDTO?: CarRouteAddDTO;
}

export interface ApiCarRouteDeleteIdDeleteRequest {
    id: string;
}

export interface ApiCarRouteGetByIdIdGetRequest {
    id: string;
}

export interface ApiCarRouteUpdatePutRequest {
    carRouteUpdateDTO?: CarRouteUpdateDTO;
}

/**
 * 
 */
export class CarRouteApi extends runtime.BaseAPI {

    /**
     */
    async apiCarRouteAddPostRaw(requestParameters: ApiCarRouteAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/CarRoute/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CarRouteAddDTOToJSON(requestParameters.carRouteAddDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCarRouteAddPost(requestParameters: ApiCarRouteAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCarRouteAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCarRouteDeleteIdDeleteRaw(requestParameters: ApiCarRouteDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiCarRouteDeleteIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/CarRoute/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCarRouteDeleteIdDelete(requestParameters: ApiCarRouteDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCarRouteDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCarRouteGetByIdIdGetRaw(requestParameters: ApiCarRouteGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CarRouteRequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiCarRouteGetByIdIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/CarRoute/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CarRouteRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCarRouteGetByIdIdGet(requestParameters: ApiCarRouteGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CarRouteRequestResponse> {
        const response = await this.apiCarRouteGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCarRouteUpdatePutRaw(requestParameters: ApiCarRouteUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/CarRoute/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CarRouteUpdateDTOToJSON(requestParameters.carRouteUpdateDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCarRouteUpdatePut(requestParameters: ApiCarRouteUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCarRouteUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
