/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingDTO
 */
export interface BookingDTO {
    /**
     * 
     * @type {string}
     * @memberof BookingDTO
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof BookingDTO
     */
    bookingDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BookingDTO
     */
    departureDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof BookingDTO
     */
    startingLocationCity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingDTO
     */
    startingLocationCountry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingDTO
     */
    finalLocationCity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingDTO
     */
    finalLocationCountry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingDTO
     */
    driverId?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingDTO
     */
    carId?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingDTO
     */
    routeId?: string;
}

/**
 * Check if a given object implements the BookingDTO interface.
 */
export function instanceOfBookingDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingDTOFromJSON(json: any): BookingDTO {
    return BookingDTOFromJSONTyped(json, false);
}

export function BookingDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'bookingDate': !exists(json, 'bookingDate') ? undefined : (new Date(json['bookingDate'])),
        'departureDate': !exists(json, 'departureDate') ? undefined : (new Date(json['departureDate'])),
        'startingLocationCity': !exists(json, 'startingLocationCity') ? undefined : json['startingLocationCity'],
        'startingLocationCountry': !exists(json, 'startingLocationCountry') ? undefined : json['startingLocationCountry'],
        'finalLocationCity': !exists(json, 'finalLocationCity') ? undefined : json['finalLocationCity'],
        'finalLocationCountry': !exists(json, 'finalLocationCountry') ? undefined : json['finalLocationCountry'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'driverId': !exists(json, 'driverId') ? undefined : json['driverId'],
        'carId': !exists(json, 'carId') ? undefined : json['carId'],
        'routeId': !exists(json, 'routeId') ? undefined : json['routeId'],
    };
}

export function BookingDTOToJSON(value?: BookingDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'bookingDate': value.bookingDate === undefined ? undefined : (value.bookingDate.toISOString()),
        'departureDate': value.departureDate === undefined ? undefined : (value.departureDate.toISOString()),
        'startingLocationCity': value.startingLocationCity,
        'startingLocationCountry': value.startingLocationCountry,
        'finalLocationCity': value.finalLocationCity,
        'finalLocationCountry': value.finalLocationCountry,
        'userId': value.userId,
        'driverId': value.driverId,
        'carId': value.carId,
        'routeId': value.routeId,
    };
}

