/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BookingDTO } from './BookingDTO';
import {
    BookingDTOFromJSON,
    BookingDTOFromJSONTyped,
    BookingDTOToJSON,
} from './BookingDTO';

/**
 * 
 * @export
 * @interface BookingDTOPagedResponse
 */
export interface BookingDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof BookingDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof BookingDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BookingDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<BookingDTO>}
     * @memberof BookingDTOPagedResponse
     */
    data?: Array<BookingDTO> | null;
}

/**
 * Check if a given object implements the BookingDTOPagedResponse interface.
 */
export function instanceOfBookingDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingDTOPagedResponseFromJSON(json: any): BookingDTOPagedResponse {
    return BookingDTOPagedResponseFromJSONTyped(json, false);
}

export function BookingDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(BookingDTOFromJSON)),
    };
}

export function BookingDTOPagedResponseToJSON(value?: BookingDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(BookingDTOToJSON)),
    };
}

