/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BookingDTOPagedResponse } from './BookingDTOPagedResponse';
import {
    BookingDTOPagedResponseFromJSON,
    BookingDTOPagedResponseFromJSONTyped,
    BookingDTOPagedResponseToJSON,
} from './BookingDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BookingDTOPagedResponseRequestResponse
 */
export interface BookingDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {BookingDTOPagedResponse}
     * @memberof BookingDTOPagedResponseRequestResponse
     */
    response?: BookingDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BookingDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the BookingDTOPagedResponseRequestResponse interface.
 */
export function instanceOfBookingDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingDTOPagedResponseRequestResponseFromJSON(json: any): BookingDTOPagedResponseRequestResponse {
    return BookingDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function BookingDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : BookingDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BookingDTOPagedResponseRequestResponseToJSON(value?: BookingDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': BookingDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

