/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Car } from './Car';
import {
    CarFromJSON,
    CarFromJSONTyped,
    CarToJSON,
} from './Car';
import type { Driver } from './Driver';
import {
    DriverFromJSON,
    DriverFromJSONTyped,
    DriverToJSON,
} from './Driver';
import type { Route } from './Route';
import {
    RouteFromJSON,
    RouteFromJSONTyped,
    RouteToJSON,
} from './Route';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Booking
 */
export interface Booking {
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Booking
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Booking
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    driverId?: string;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    carId?: string;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    routeId?: string;
    /**
     * 
     * @type {Date}
     * @memberof Booking
     */
    bookingDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Booking
     */
    departureDate?: Date;
    /**
     * 
     * @type {User}
     * @memberof Booking
     */
    user?: User;
    /**
     * 
     * @type {Driver}
     * @memberof Booking
     */
    driver?: Driver;
    /**
     * 
     * @type {Car}
     * @memberof Booking
     */
    car?: Car;
    /**
     * 
     * @type {Route}
     * @memberof Booking
     */
    route?: Route;
}

/**
 * Check if a given object implements the Booking interface.
 */
export function instanceOfBooking(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingFromJSON(json: any): Booking {
    return BookingFromJSONTyped(json, false);
}

export function BookingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Booking {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'driverId': !exists(json, 'driverId') ? undefined : json['driverId'],
        'carId': !exists(json, 'carId') ? undefined : json['carId'],
        'routeId': !exists(json, 'routeId') ? undefined : json['routeId'],
        'bookingDate': !exists(json, 'bookingDate') ? undefined : (new Date(json['bookingDate'])),
        'departureDate': !exists(json, 'departureDate') ? undefined : (new Date(json['departureDate'])),
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
        'driver': !exists(json, 'driver') ? undefined : DriverFromJSON(json['driver']),
        'car': !exists(json, 'car') ? undefined : CarFromJSON(json['car']),
        'route': !exists(json, 'route') ? undefined : RouteFromJSON(json['route']),
    };
}

export function BookingToJSON(value?: Booking | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'userId': value.userId,
        'driverId': value.driverId,
        'carId': value.carId,
        'routeId': value.routeId,
        'bookingDate': value.bookingDate === undefined ? undefined : (value.bookingDate.toISOString()),
        'departureDate': value.departureDate === undefined ? undefined : (value.departureDate.toISOString()),
        'user': UserToJSON(value.user),
        'driver': DriverToJSON(value.driver),
        'car': CarToJSON(value.car),
        'route': RouteToJSON(value.route),
    };
}

