/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingUpdateDTO
 */
export interface BookingUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof BookingUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof BookingUpdateDTO
     */
    bookingDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BookingUpdateDTO
     */
    departureDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof BookingUpdateDTO
     */
    departurePlace?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingUpdateDTO
     */
    arrivalPlace?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingUpdateDTO
     */
    driverId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingUpdateDTO
     */
    carId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingUpdateDTO
     */
    routeId?: string | null;
}

/**
 * Check if a given object implements the BookingUpdateDTO interface.
 */
export function instanceOfBookingUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingUpdateDTOFromJSON(json: any): BookingUpdateDTO {
    return BookingUpdateDTOFromJSONTyped(json, false);
}

export function BookingUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'bookingDate': !exists(json, 'bookingDate') ? undefined : (json['bookingDate'] === null ? null : new Date(json['bookingDate'])),
        'departureDate': !exists(json, 'departureDate') ? undefined : (json['departureDate'] === null ? null : new Date(json['departureDate'])),
        'departurePlace': !exists(json, 'departurePlace') ? undefined : json['departurePlace'],
        'arrivalPlace': !exists(json, 'arrivalPlace') ? undefined : json['arrivalPlace'],
        'driverId': !exists(json, 'driverId') ? undefined : json['driverId'],
        'carId': !exists(json, 'carId') ? undefined : json['carId'],
        'routeId': !exists(json, 'routeId') ? undefined : json['routeId'],
    };
}

export function BookingUpdateDTOToJSON(value?: BookingUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'bookingDate': value.bookingDate === undefined ? undefined : (value.bookingDate === null ? null : value.bookingDate.toISOString()),
        'departureDate': value.departureDate === undefined ? undefined : (value.departureDate === null ? null : value.departureDate.toISOString()),
        'departurePlace': value.departurePlace,
        'arrivalPlace': value.arrivalPlace,
        'driverId': value.driverId,
        'carId': value.carId,
        'routeId': value.routeId,
    };
}

