/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingAddDTO
 */
export interface BookingAddDTO {
    /**
     * 
     * @type {string}
     * @memberof BookingAddDTO
     */
    driverId?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingAddDTO
     */
    routeName?: string;
    /**
     * 
     * @type {Date}
     * @memberof BookingAddDTO
     */
    bookingDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BookingAddDTO
     */
    departureDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof BookingAddDTO
     */
    departurePlace?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingAddDTO
     */
    arrivalPlace?: string | null;
}

/**
 * Check if a given object implements the BookingAddDTO interface.
 */
export function instanceOfBookingAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingAddDTOFromJSON(json: any): BookingAddDTO {
    return BookingAddDTOFromJSONTyped(json, false);
}

export function BookingAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'driverId': !exists(json, 'driverId') ? undefined : json['driverId'],
        'routeName': !exists(json, 'routeName') ? undefined : json['routeName'],
        'bookingDate': !exists(json, 'bookingDate') ? undefined : (new Date(json['bookingDate'])),
        'departureDate': !exists(json, 'departureDate') ? undefined : (new Date(json['departureDate'])),
        'departurePlace': !exists(json, 'departurePlace') ? undefined : json['departurePlace'],
        'arrivalPlace': !exists(json, 'arrivalPlace') ? undefined : json['arrivalPlace'],
    };
}

export function BookingAddDTOToJSON(value?: BookingAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'driverId': value.driverId,
        'routeName': value.routeName,
        'bookingDate': value.bookingDate === undefined ? undefined : (value.bookingDate.toISOString()),
        'departureDate': value.departureDate === undefined ? undefined : (value.departureDate.toISOString()),
        'departurePlace': value.departurePlace,
        'arrivalPlace': value.arrivalPlace,
    };
}

