/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Booking } from './Booking';
import {
    BookingFromJSON,
    BookingFromJSONTyped,
    BookingToJSON,
} from './Booking';
import type { CarRoute } from './CarRoute';
import {
    CarRouteFromJSON,
    CarRouteFromJSONTyped,
    CarRouteToJSON,
} from './CarRoute';

/**
 * 
 * @export
 * @interface Car
 */
export interface Car {
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Car
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Car
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    model?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    registrationNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Car
     */
    numberOfSeats?: number;
    /**
     * 
     * @type {Array<Booking>}
     * @memberof Car
     */
    bookings?: Array<Booking> | null;
    /**
     * 
     * @type {Array<CarRoute>}
     * @memberof Car
     */
    carRoutes?: Array<CarRoute> | null;
}

/**
 * Check if a given object implements the Car interface.
 */
export function instanceOfCar(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CarFromJSON(json: any): Car {
    return CarFromJSONTyped(json, false);
}

export function CarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Car {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'brand': !exists(json, 'brand') ? undefined : json['brand'],
        'model': !exists(json, 'model') ? undefined : json['model'],
        'registrationNumber': !exists(json, 'registrationNumber') ? undefined : json['registrationNumber'],
        'numberOfSeats': !exists(json, 'numberOfSeats') ? undefined : json['numberOfSeats'],
        'bookings': !exists(json, 'bookings') ? undefined : (json['bookings'] === null ? null : (json['bookings'] as Array<any>).map(BookingFromJSON)),
        'carRoutes': !exists(json, 'carRoutes') ? undefined : (json['carRoutes'] === null ? null : (json['carRoutes'] as Array<any>).map(CarRouteFromJSON)),
    };
}

export function CarToJSON(value?: Car | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'brand': value.brand,
        'model': value.model,
        'registrationNumber': value.registrationNumber,
        'numberOfSeats': value.numberOfSeats,
        'bookings': value.bookings === undefined ? undefined : (value.bookings === null ? null : (value.bookings as Array<any>).map(BookingToJSON)),
        'carRoutes': value.carRoutes === undefined ? undefined : (value.carRoutes === null ? null : (value.carRoutes as Array<any>).map(CarRouteToJSON)),
    };
}

