/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CarAddDTO
 */
export interface CarAddDTO {
    /**
     * 
     * @type {string}
     * @memberof CarAddDTO
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CarAddDTO
     */
    model?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CarAddDTO
     */
    registrationNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CarAddDTO
     */
    numberOfSeats?: number;
}

/**
 * Check if a given object implements the CarAddDTO interface.
 */
export function instanceOfCarAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CarAddDTOFromJSON(json: any): CarAddDTO {
    return CarAddDTOFromJSONTyped(json, false);
}

export function CarAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'brand': !exists(json, 'brand') ? undefined : json['brand'],
        'model': !exists(json, 'model') ? undefined : json['model'],
        'registrationNumber': !exists(json, 'registrationNumber') ? undefined : json['registrationNumber'],
        'numberOfSeats': !exists(json, 'numberOfSeats') ? undefined : json['numberOfSeats'],
    };
}

export function CarAddDTOToJSON(value?: CarAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'brand': value.brand,
        'model': value.model,
        'registrationNumber': value.registrationNumber,
        'numberOfSeats': value.numberOfSeats,
    };
}

