/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CarDTO } from './CarDTO';
import {
    CarDTOFromJSON,
    CarDTOFromJSONTyped,
    CarDTOToJSON,
} from './CarDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CarDTORequestResponse
 */
export interface CarDTORequestResponse {
    /**
     * 
     * @type {CarDTO}
     * @memberof CarDTORequestResponse
     */
    response?: CarDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CarDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the CarDTORequestResponse interface.
 */
export function instanceOfCarDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CarDTORequestResponseFromJSON(json: any): CarDTORequestResponse {
    return CarDTORequestResponseFromJSONTyped(json, false);
}

export function CarDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : CarDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CarDTORequestResponseToJSON(value?: CarDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': CarDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

