/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CarDTO } from './CarDTO';
import {
    CarDTOFromJSON,
    CarDTOFromJSONTyped,
    CarDTOToJSON,
} from './CarDTO';

/**
 * 
 * @export
 * @interface CarDTOPagedResponse
 */
export interface CarDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof CarDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof CarDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof CarDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<CarDTO>}
     * @memberof CarDTOPagedResponse
     */
    data?: Array<CarDTO> | null;
}

/**
 * Check if a given object implements the CarDTOPagedResponse interface.
 */
export function instanceOfCarDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CarDTOPagedResponseFromJSON(json: any): CarDTOPagedResponse {
    return CarDTOPagedResponseFromJSONTyped(json, false);
}

export function CarDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(CarDTOFromJSON)),
    };
}

export function CarDTOPagedResponseToJSON(value?: CarDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(CarDTOToJSON)),
    };
}

