/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CarDTOPagedResponse } from './CarDTOPagedResponse';
import {
    CarDTOPagedResponseFromJSON,
    CarDTOPagedResponseFromJSONTyped,
    CarDTOPagedResponseToJSON,
} from './CarDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CarDTOPagedResponseRequestResponse
 */
export interface CarDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {CarDTOPagedResponse}
     * @memberof CarDTOPagedResponseRequestResponse
     */
    response?: CarDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CarDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the CarDTOPagedResponseRequestResponse interface.
 */
export function instanceOfCarDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CarDTOPagedResponseRequestResponseFromJSON(json: any): CarDTOPagedResponseRequestResponse {
    return CarDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function CarDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : CarDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CarDTOPagedResponseRequestResponseToJSON(value?: CarDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': CarDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

