/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CarRouteUpdateDTO
 */
export interface CarRouteUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof CarRouteUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CarRouteUpdateDTO
     */
    routeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CarRouteUpdateDTO
     */
    carId?: string | null;
}

/**
 * Check if a given object implements the CarRouteUpdateDTO interface.
 */
export function instanceOfCarRouteUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CarRouteUpdateDTOFromJSON(json: any): CarRouteUpdateDTO {
    return CarRouteUpdateDTOFromJSONTyped(json, false);
}

export function CarRouteUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarRouteUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'routeId': !exists(json, 'routeId') ? undefined : json['routeId'],
        'carId': !exists(json, 'carId') ? undefined : json['carId'],
    };
}

export function CarRouteUpdateDTOToJSON(value?: CarRouteUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'routeId': value.routeId,
        'carId': value.carId,
    };
}

