/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CarRouteAddDTO
 */
export interface CarRouteAddDTO {
    /**
     * 
     * @type {string}
     * @memberof CarRouteAddDTO
     */
    carId?: string;
    /**
     * 
     * @type {string}
     * @memberof CarRouteAddDTO
     */
    routeId?: string;
}

/**
 * Check if a given object implements the CarRouteAddDTO interface.
 */
export function instanceOfCarRouteAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CarRouteAddDTOFromJSON(json: any): CarRouteAddDTO {
    return CarRouteAddDTOFromJSONTyped(json, false);
}

export function CarRouteAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarRouteAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'carId': !exists(json, 'carId') ? undefined : json['carId'],
        'routeId': !exists(json, 'routeId') ? undefined : json['routeId'],
    };
}

export function CarRouteAddDTOToJSON(value?: CarRouteAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'carId': value.carId,
        'routeId': value.routeId,
    };
}

