/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CarRoute } from './CarRoute';
import {
    CarRouteFromJSON,
    CarRouteFromJSONTyped,
    CarRouteToJSON,
} from './CarRoute';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CarRouteRequestResponse
 */
export interface CarRouteRequestResponse {
    /**
     * 
     * @type {CarRoute}
     * @memberof CarRouteRequestResponse
     */
    response?: CarRoute;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CarRouteRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the CarRouteRequestResponse interface.
 */
export function instanceOfCarRouteRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CarRouteRequestResponseFromJSON(json: any): CarRouteRequestResponse {
    return CarRouteRequestResponseFromJSONTyped(json, false);
}

export function CarRouteRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarRouteRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : CarRouteFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CarRouteRequestResponseToJSON(value?: CarRouteRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': CarRouteToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

