/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CarUpdateDTO
 */
export interface CarUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof CarUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CarUpdateDTO
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CarUpdateDTO
     */
    model?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CarUpdateDTO
     */
    numberOfSeats?: number | null;
}

/**
 * Check if a given object implements the CarUpdateDTO interface.
 */
export function instanceOfCarUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CarUpdateDTOFromJSON(json: any): CarUpdateDTO {
    return CarUpdateDTOFromJSONTyped(json, false);
}

export function CarUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'brand': !exists(json, 'brand') ? undefined : json['brand'],
        'model': !exists(json, 'model') ? undefined : json['model'],
        'numberOfSeats': !exists(json, 'numberOfSeats') ? undefined : json['numberOfSeats'],
    };
}

export function CarUpdateDTOToJSON(value?: CarUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'brand': value.brand,
        'model': value.model,
        'numberOfSeats': value.numberOfSeats,
    };
}

