/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DriverInfoAddDTO
 */
export interface DriverInfoAddDTO {
    /**
     * 
     * @type {number}
     * @memberof DriverInfoAddDTO
     */
    completedTrips?: number;
    /**
     * 
     * @type {number}
     * @memberof DriverInfoAddDTO
     */
    yearExperience?: number;
    /**
     * 
     * @type {Date}
     * @memberof DriverInfoAddDTO
     */
    birthDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof DriverInfoAddDTO
     */
    driverId?: string;
}

/**
 * Check if a given object implements the DriverInfoAddDTO interface.
 */
export function instanceOfDriverInfoAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DriverInfoAddDTOFromJSON(json: any): DriverInfoAddDTO {
    return DriverInfoAddDTOFromJSONTyped(json, false);
}

export function DriverInfoAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriverInfoAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'completedTrips': !exists(json, 'completedTrips') ? undefined : json['completedTrips'],
        'yearExperience': !exists(json, 'yearExperience') ? undefined : json['yearExperience'],
        'birthDate': !exists(json, 'birthDate') ? undefined : (new Date(json['birthDate'])),
        'driverId': !exists(json, 'driverId') ? undefined : json['driverId'],
    };
}

export function DriverInfoAddDTOToJSON(value?: DriverInfoAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'completedTrips': value.completedTrips,
        'yearExperience': value.yearExperience,
        'birthDate': value.birthDate === undefined ? undefined : (value.birthDate.toISOString()),
        'driverId': value.driverId,
    };
}

