/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DriverDTOPagedResponse } from './DriverDTOPagedResponse';
import {
    DriverDTOPagedResponseFromJSON,
    DriverDTOPagedResponseFromJSONTyped,
    DriverDTOPagedResponseToJSON,
} from './DriverDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface DriverDTOPagedResponseRequestResponse
 */
export interface DriverDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {DriverDTOPagedResponse}
     * @memberof DriverDTOPagedResponseRequestResponse
     */
    response?: DriverDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof DriverDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the DriverDTOPagedResponseRequestResponse interface.
 */
export function instanceOfDriverDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DriverDTOPagedResponseRequestResponseFromJSON(json: any): DriverDTOPagedResponseRequestResponse {
    return DriverDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function DriverDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriverDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : DriverDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function DriverDTOPagedResponseRequestResponseToJSON(value?: DriverDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': DriverDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

