/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Booking } from './Booking';
import {
    BookingFromJSON,
    BookingFromJSONTyped,
    BookingToJSON,
} from './Booking';
import type { DriverInfo } from './DriverInfo';
import {
    DriverInfoFromJSON,
    DriverInfoFromJSONTyped,
    DriverInfoToJSON,
} from './DriverInfo';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
} from './UserRoleEnum';

/**
 * 
 * @export
 * @interface Driver
 */
export interface Driver {
    /**
     * 
     * @type {string}
     * @memberof Driver
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Driver
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Driver
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Driver
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Driver
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Driver
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Driver
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof Driver
     */
    role?: UserRoleEnum;
    /**
     * 
     * @type {Array<Booking>}
     * @memberof Driver
     */
    bookings?: Array<Booking> | null;
    /**
     * 
     * @type {DriverInfo}
     * @memberof Driver
     */
    driverInfo?: DriverInfo;
}

/**
 * Check if a given object implements the Driver interface.
 */
export function instanceOfDriver(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DriverFromJSON(json: any): Driver {
    return DriverFromJSONTyped(json, false);
}

export function DriverFromJSONTyped(json: any, ignoreDiscriminator: boolean): Driver {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'role': !exists(json, 'role') ? undefined : UserRoleEnumFromJSON(json['role']),
        'bookings': !exists(json, 'bookings') ? undefined : (json['bookings'] === null ? null : (json['bookings'] as Array<any>).map(BookingFromJSON)),
        'driverInfo': !exists(json, 'driverInfo') ? undefined : DriverInfoFromJSON(json['driverInfo']),
    };
}

export function DriverToJSON(value?: Driver | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'name': value.name,
        'email': value.email,
        'password': value.password,
        'phoneNumber': value.phoneNumber,
        'role': UserRoleEnumToJSON(value.role),
        'bookings': value.bookings === undefined ? undefined : (value.bookings === null ? null : (value.bookings as Array<any>).map(BookingToJSON)),
        'driverInfo': DriverInfoToJSON(value.driverInfo),
    };
}

