/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DriverDTO } from './DriverDTO';
import {
    DriverDTOFromJSON,
    DriverDTOFromJSONTyped,
    DriverDTOToJSON,
} from './DriverDTO';

/**
 * 
 * @export
 * @interface DriverInfoDTO
 */
export interface DriverInfoDTO {
    /**
     * 
     * @type {number}
     * @memberof DriverInfoDTO
     */
    completedTrips?: number;
    /**
     * 
     * @type {number}
     * @memberof DriverInfoDTO
     */
    yearExperience?: number;
    /**
     * 
     * @type {Date}
     * @memberof DriverInfoDTO
     */
    birthDate?: Date;
    /**
     * 
     * @type {DriverDTO}
     * @memberof DriverInfoDTO
     */
    driver?: DriverDTO;
}

/**
 * Check if a given object implements the DriverInfoDTO interface.
 */
export function instanceOfDriverInfoDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DriverInfoDTOFromJSON(json: any): DriverInfoDTO {
    return DriverInfoDTOFromJSONTyped(json, false);
}

export function DriverInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriverInfoDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'completedTrips': !exists(json, 'completedTrips') ? undefined : json['completedTrips'],
        'yearExperience': !exists(json, 'yearExperience') ? undefined : json['yearExperience'],
        'birthDate': !exists(json, 'birthDate') ? undefined : (new Date(json['birthDate'])),
        'driver': !exists(json, 'driver') ? undefined : DriverDTOFromJSON(json['driver']),
    };
}

export function DriverInfoDTOToJSON(value?: DriverInfoDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'completedTrips': value.completedTrips,
        'yearExperience': value.yearExperience,
        'birthDate': value.birthDate === undefined ? undefined : (value.birthDate.toISOString()),
        'driver': DriverDTOToJSON(value.driver),
    };
}

