/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DriverInfoDTO } from './DriverInfoDTO';
import {
    DriverInfoDTOFromJSON,
    DriverInfoDTOFromJSONTyped,
    DriverInfoDTOToJSON,
} from './DriverInfoDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface DriverInfoDTORequestResponse
 */
export interface DriverInfoDTORequestResponse {
    /**
     * 
     * @type {DriverInfoDTO}
     * @memberof DriverInfoDTORequestResponse
     */
    response?: DriverInfoDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof DriverInfoDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the DriverInfoDTORequestResponse interface.
 */
export function instanceOfDriverInfoDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DriverInfoDTORequestResponseFromJSON(json: any): DriverInfoDTORequestResponse {
    return DriverInfoDTORequestResponseFromJSONTyped(json, false);
}

export function DriverInfoDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriverInfoDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : DriverInfoDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function DriverInfoDTORequestResponseToJSON(value?: DriverInfoDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': DriverInfoDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

