/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Driver } from './Driver';
import {
    DriverFromJSON,
    DriverFromJSONTyped,
    DriverToJSON,
} from './Driver';

/**
 * 
 * @export
 * @interface DriverInfo
 */
export interface DriverInfo {
    /**
     * 
     * @type {string}
     * @memberof DriverInfo
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof DriverInfo
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DriverInfo
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof DriverInfo
     */
    completedTrips?: number;
    /**
     * 
     * @type {number}
     * @memberof DriverInfo
     */
    yearExperience?: number;
    /**
     * 
     * @type {Date}
     * @memberof DriverInfo
     */
    birthDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof DriverInfo
     */
    driverId?: string;
    /**
     * 
     * @type {Driver}
     * @memberof DriverInfo
     */
    driver?: Driver;
}

/**
 * Check if a given object implements the DriverInfo interface.
 */
export function instanceOfDriverInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DriverInfoFromJSON(json: any): DriverInfo {
    return DriverInfoFromJSONTyped(json, false);
}

export function DriverInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriverInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'completedTrips': !exists(json, 'completedTrips') ? undefined : json['completedTrips'],
        'yearExperience': !exists(json, 'yearExperience') ? undefined : json['yearExperience'],
        'birthDate': !exists(json, 'birthDate') ? undefined : (new Date(json['birthDate'])),
        'driverId': !exists(json, 'driverId') ? undefined : json['driverId'],
        'driver': !exists(json, 'driver') ? undefined : DriverFromJSON(json['driver']),
    };
}

export function DriverInfoToJSON(value?: DriverInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'completedTrips': value.completedTrips,
        'yearExperience': value.yearExperience,
        'birthDate': value.birthDate === undefined ? undefined : (value.birthDate.toISOString()),
        'driverId': value.driverId,
        'driver': DriverToJSON(value.driver),
    };
}

