/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { LocationDTO } from './LocationDTO';
import {
    LocationDTOFromJSON,
    LocationDTOFromJSONTyped,
    LocationDTOToJSON,
} from './LocationDTO';

/**
 * 
 * @export
 * @interface LocationDTOListRequestResponse
 */
export interface LocationDTOListRequestResponse {
    /**
     * 
     * @type {Array<LocationDTO>}
     * @memberof LocationDTOListRequestResponse
     */
    readonly response?: Array<LocationDTO> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof LocationDTOListRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the LocationDTOListRequestResponse interface.
 */
export function instanceOfLocationDTOListRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LocationDTOListRequestResponseFromJSON(json: any): LocationDTOListRequestResponse {
    return LocationDTOListRequestResponseFromJSONTyped(json, false);
}

export function LocationDTOListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationDTOListRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : (json['response'] === null ? null : (json['response'] as Array<any>).map(LocationDTOFromJSON)),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function LocationDTOListRequestResponseToJSON(value?: LocationDTOListRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

