/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationDTO
 */
export interface LocationDTO {
    /**
     * 
     * @type {string}
     * @memberof LocationDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LocationDTO
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationDTO
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationDTO
     */
    adress?: string | null;
}

/**
 * Check if a given object implements the LocationDTO interface.
 */
export function instanceOfLocationDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LocationDTOFromJSON(json: any): LocationDTO {
    return LocationDTOFromJSONTyped(json, false);
}

export function LocationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'adress': !exists(json, 'adress') ? undefined : json['adress'],
    };
}

export function LocationDTOToJSON(value?: LocationDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'city': value.city,
        'country': value.country,
        'adress': value.adress,
    };
}

