/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CarDTO } from './CarDTO';
import {
    CarDTOFromJSON,
    CarDTOFromJSONTyped,
    CarDTOToJSON,
} from './CarDTO';

/**
 * 
 * @export
 * @interface RouteDTO
 */
export interface RouteDTO {
    /**
     * 
     * @type {string}
     * @memberof RouteDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RouteDTO
     */
    startingLocationCity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDTO
     */
    startingLocationCountry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDTO
     */
    finalLocationCity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDTO
     */
    finalLocationCountry?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RouteDTO
     */
    departureTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RouteDTO
     */
    arrivalTime?: Date;
    /**
     * 
     * @type {Array<CarDTO>}
     * @memberof RouteDTO
     */
    assignedCars?: Array<CarDTO> | null;
}

/**
 * Check if a given object implements the RouteDTO interface.
 */
export function instanceOfRouteDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RouteDTOFromJSON(json: any): RouteDTO {
    return RouteDTOFromJSONTyped(json, false);
}

export function RouteDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'startingLocationCity': !exists(json, 'startingLocationCity') ? undefined : json['startingLocationCity'],
        'startingLocationCountry': !exists(json, 'startingLocationCountry') ? undefined : json['startingLocationCountry'],
        'finalLocationCity': !exists(json, 'finalLocationCity') ? undefined : json['finalLocationCity'],
        'finalLocationCountry': !exists(json, 'finalLocationCountry') ? undefined : json['finalLocationCountry'],
        'departureTime': !exists(json, 'departureTime') ? undefined : (new Date(json['departureTime'])),
        'arrivalTime': !exists(json, 'arrivalTime') ? undefined : (new Date(json['arrivalTime'])),
        'assignedCars': !exists(json, 'assignedCars') ? undefined : (json['assignedCars'] === null ? null : (json['assignedCars'] as Array<any>).map(CarDTOFromJSON)),
    };
}

export function RouteDTOToJSON(value?: RouteDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'startingLocationCity': value.startingLocationCity,
        'startingLocationCountry': value.startingLocationCountry,
        'finalLocationCity': value.finalLocationCity,
        'finalLocationCountry': value.finalLocationCountry,
        'departureTime': value.departureTime === undefined ? undefined : (value.departureTime.toISOString()),
        'arrivalTime': value.arrivalTime === undefined ? undefined : (value.arrivalTime.toISOString()),
        'assignedCars': value.assignedCars === undefined ? undefined : (value.assignedCars === null ? null : (value.assignedCars as Array<any>).map(CarDTOToJSON)),
    };
}

