/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { RouteDTOPagedResponse } from './RouteDTOPagedResponse';
import {
    RouteDTOPagedResponseFromJSON,
    RouteDTOPagedResponseFromJSONTyped,
    RouteDTOPagedResponseToJSON,
} from './RouteDTOPagedResponse';

/**
 * 
 * @export
 * @interface RouteDTOPagedResponseRequestResponse
 */
export interface RouteDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {RouteDTOPagedResponse}
     * @memberof RouteDTOPagedResponseRequestResponse
     */
    response?: RouteDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RouteDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the RouteDTOPagedResponseRequestResponse interface.
 */
export function instanceOfRouteDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RouteDTOPagedResponseRequestResponseFromJSON(json: any): RouteDTOPagedResponseRequestResponse {
    return RouteDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function RouteDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : RouteDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RouteDTOPagedResponseRequestResponseToJSON(value?: RouteDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': RouteDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

