/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RouteAddDTO
 */
export interface RouteAddDTO {
    /**
     * 
     * @type {string}
     * @memberof RouteAddDTO
     */
    startingLocationCity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteAddDTO
     */
    startingLocationCountry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteAddDTO
     */
    finalLocationCity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteAddDTO
     */
    finalLocationCountry?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RouteAddDTO
     */
    departureTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RouteAddDTO
     */
    arrivalTime?: Date;
}

/**
 * Check if a given object implements the RouteAddDTO interface.
 */
export function instanceOfRouteAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RouteAddDTOFromJSON(json: any): RouteAddDTO {
    return RouteAddDTOFromJSONTyped(json, false);
}

export function RouteAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startingLocationCity': !exists(json, 'startingLocationCity') ? undefined : json['startingLocationCity'],
        'startingLocationCountry': !exists(json, 'startingLocationCountry') ? undefined : json['startingLocationCountry'],
        'finalLocationCity': !exists(json, 'finalLocationCity') ? undefined : json['finalLocationCity'],
        'finalLocationCountry': !exists(json, 'finalLocationCountry') ? undefined : json['finalLocationCountry'],
        'departureTime': !exists(json, 'departureTime') ? undefined : (new Date(json['departureTime'])),
        'arrivalTime': !exists(json, 'arrivalTime') ? undefined : (new Date(json['arrivalTime'])),
    };
}

export function RouteAddDTOToJSON(value?: RouteAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startingLocationCity': value.startingLocationCity,
        'startingLocationCountry': value.startingLocationCountry,
        'finalLocationCity': value.finalLocationCity,
        'finalLocationCountry': value.finalLocationCountry,
        'departureTime': value.departureTime === undefined ? undefined : (value.departureTime.toISOString()),
        'arrivalTime': value.arrivalTime === undefined ? undefined : (value.arrivalTime.toISOString()),
    };
}

