/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RouteDTO
 */
export interface RouteDTO {
    /**
     * 
     * @type {string}
     * @memberof RouteDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RouteDTO
     */
    routeName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDTO
     */
    routeLength?: string | null;
}

/**
 * Check if a given object implements the RouteDTO interface.
 */
export function instanceOfRouteDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RouteDTOFromJSON(json: any): RouteDTO {
    return RouteDTOFromJSONTyped(json, false);
}

export function RouteDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'routeName': !exists(json, 'routeName') ? undefined : json['routeName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'routeLength': !exists(json, 'routeLength') ? undefined : json['routeLength']
    };
}

export function RouteDTOToJSON(value?: RouteDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'routeName': value.routeName,
        'description': value.description,
        'routeLength': value.routeLength
    };
}

