/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RouteDTO } from './RouteDTO';
import {
    RouteDTOFromJSON,
    RouteDTOFromJSONTyped,
    RouteDTOToJSON,
} from './RouteDTO';

/**
 * 
 * @export
 * @interface RouteDTOPagedResponse
 */
export interface RouteDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof RouteDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof RouteDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof RouteDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<RouteDTO>}
     * @memberof RouteDTOPagedResponse
     */
    data?: Array<RouteDTO> | null;
}

/**
 * Check if a given object implements the RouteDTOPagedResponse interface.
 */
export function instanceOfRouteDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RouteDTOPagedResponseFromJSON(json: any): RouteDTOPagedResponse {
    return RouteDTOPagedResponseFromJSONTyped(json, false);
}

export function RouteDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(RouteDTOFromJSON)),
    };
}

export function RouteDTOPagedResponseToJSON(value?: RouteDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(RouteDTOToJSON)),
    };
}

