/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RouteUpdateDTO
 */
export interface RouteUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof RouteUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RouteUpdateDTO
     */
    startingLocationId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteUpdateDTO
     */
    finalLocationId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RouteUpdateDTO
     */
    departureTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RouteUpdateDTO
     */
    arrivalTime?: Date | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof RouteUpdateDTO
     */
    carIds?: Array<string> | null;
}

/**
 * Check if a given object implements the RouteUpdateDTO interface.
 */
export function instanceOfRouteUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RouteUpdateDTOFromJSON(json: any): RouteUpdateDTO {
    return RouteUpdateDTOFromJSONTyped(json, false);
}

export function RouteUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'startingLocationId': !exists(json, 'startingLocationId') ? undefined : json['startingLocationId'],
        'finalLocationId': !exists(json, 'finalLocationId') ? undefined : json['finalLocationId'],
        'departureTime': !exists(json, 'departureTime') ? undefined : (json['departureTime'] === null ? null : new Date(json['departureTime'])),
        'arrivalTime': !exists(json, 'arrivalTime') ? undefined : (json['arrivalTime'] === null ? null : new Date(json['arrivalTime'])),
        'carIds': !exists(json, 'carIds') ? undefined : json['carIds'],
    };
}

export function RouteUpdateDTOToJSON(value?: RouteUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'startingLocationId': value.startingLocationId,
        'finalLocationId': value.finalLocationId,
        'departureTime': value.departureTime === undefined ? undefined : (value.departureTime === null ? null : value.departureTime.toISOString()),
        'arrivalTime': value.arrivalTime === undefined ? undefined : (value.arrivalTime === null ? null : value.arrivalTime.toISOString()),
        'carIds': value.carIds,
    };
}

