/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { RouteDTO } from './RouteDTO';
import {
    RouteDTOFromJSON,
    RouteDTOFromJSONTyped,
    RouteDTOToJSON,
} from './RouteDTO';

/**
 * 
 * @export
 * @interface RouteDTORequestResponse
 */
export interface RouteDTORequestResponse {
    /**
     * 
     * @type {RouteDTO}
     * @memberof RouteDTORequestResponse
     */
    response?: RouteDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RouteDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the RouteDTORequestResponse interface.
 */
export function instanceOfRouteDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RouteDTORequestResponseFromJSON(json: any): RouteDTORequestResponse {
    return RouteDTORequestResponseFromJSONTyped(json, false);
}

export function RouteDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : RouteDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RouteDTORequestResponseToJSON(value?: RouteDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': RouteDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

