/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { RouteDTO } from './RouteDTO';
import {
    RouteDTOFromJSON,
    RouteDTOFromJSONTyped,
    RouteDTOToJSON,
} from './RouteDTO';

/**
 * 
 * @export
 * @interface StringRouteDTOListDictionaryRequestResponse
 */
export interface StringRouteDTOListDictionaryRequestResponse {
    /**
     * 
     * @type {{ [key: string]: Array<RouteDTO>; }}
     * @memberof StringRouteDTOListDictionaryRequestResponse
     */
    readonly response?: { [key: string]: Array<RouteDTO>; } | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof StringRouteDTOListDictionaryRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the StringRouteDTOListDictionaryRequestResponse interface.
 */
export function instanceOfStringRouteDTOListDictionaryRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StringRouteDTOListDictionaryRequestResponseFromJSON(json: any): StringRouteDTOListDictionaryRequestResponse {
    return StringRouteDTOListDictionaryRequestResponseFromJSONTyped(json, false);
}

export function StringRouteDTOListDictionaryRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StringRouteDTOListDictionaryRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : json['response'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function StringRouteDTOListDictionaryRequestResponseToJSON(value?: StringRouteDTOListDictionaryRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

