/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BookingDTO } from './BookingDTO';
import {
    BookingDTOFromJSON,
    BookingDTOFromJSONTyped,
    BookingDTOToJSON,
} from './BookingDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BookingDTORequestResponse
 */
export interface BookingDTORequestResponse {
    /**
     * 
     * @type {BookingDTO}
     * @memberof BookingDTORequestResponse
     */
    response?: BookingDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BookingDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the BookingDTORequestResponse interface.
 */
export function instanceOfBookingDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingDTORequestResponseFromJSON(json: any): BookingDTORequestResponse {
    return BookingDTORequestResponseFromJSONTyped(json, false);
}

export function BookingDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : BookingDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BookingDTORequestResponseToJSON(value?: BookingDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': BookingDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

