/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Car } from './Car';
import {
    CarFromJSON,
    CarFromJSONTyped,
    CarToJSON,
} from './Car';
import type { Route } from './Route';
import {
    RouteFromJSON,
    RouteFromJSONTyped,
    RouteToJSON,
} from './Route';

/**
 * 
 * @export
 * @interface CarRoute
 */
export interface CarRoute {
    /**
     * 
     * @type {string}
     * @memberof CarRoute
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CarRoute
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CarRoute
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CarRoute
     */
    carId?: string;
    /**
     * 
     * @type {Car}
     * @memberof CarRoute
     */
    car?: Car;
    /**
     * 
     * @type {string}
     * @memberof CarRoute
     */
    routeId?: string;
    /**
     * 
     * @type {Route}
     * @memberof CarRoute
     */
    route?: Route;
}

/**
 * Check if a given object implements the CarRoute interface.
 */
export function instanceOfCarRoute(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CarRouteFromJSON(json: any): CarRoute {
    return CarRouteFromJSONTyped(json, false);
}

export function CarRouteFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarRoute {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'carId': !exists(json, 'carId') ? undefined : json['carId'],
        'car': !exists(json, 'car') ? undefined : CarFromJSON(json['car']),
        'routeId': !exists(json, 'routeId') ? undefined : json['routeId'],
        'route': !exists(json, 'route') ? undefined : RouteFromJSON(json['route']),
    };
}

export function CarRouteToJSON(value?: CarRoute | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'carId': value.carId,
        'car': CarToJSON(value.car),
        'routeId': value.routeId,
        'route': RouteToJSON(value.route),
    };
}

