/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DriverDTO } from './DriverDTO';
import {
    DriverDTOFromJSON,
    DriverDTOFromJSONTyped,
    DriverDTOToJSON,
} from './DriverDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface DriverDTORequestResponse
 */
export interface DriverDTORequestResponse {
    /**
     * 
     * @type {DriverDTO}
     * @memberof DriverDTORequestResponse
     */
    response?: DriverDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof DriverDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the DriverDTORequestResponse interface.
 */
export function instanceOfDriverDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DriverDTORequestResponseFromJSON(json: any): DriverDTORequestResponse {
    return DriverDTORequestResponseFromJSONTyped(json, false);
}

export function DriverDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriverDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : DriverDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function DriverDTORequestResponseToJSON(value?: DriverDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': DriverDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

