/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DriverInfoUpdateDTO
 */
export interface DriverInfoUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof DriverInfoUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof DriverInfoUpdateDTO
     */
    completedTrips?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DriverInfoUpdateDTO
     */
    yearExperience?: number | null;
}

/**
 * Check if a given object implements the DriverInfoUpdateDTO interface.
 */
export function instanceOfDriverInfoUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DriverInfoUpdateDTOFromJSON(json: any): DriverInfoUpdateDTO {
    return DriverInfoUpdateDTOFromJSONTyped(json, false);
}

export function DriverInfoUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriverInfoUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'completedTrips': !exists(json, 'completedTrips') ? undefined : json['completedTrips'],
        'yearExperience': !exists(json, 'yearExperience') ? undefined : json['yearExperience'],
    };
}

export function DriverInfoUpdateDTOToJSON(value?: DriverInfoUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'completedTrips': value.completedTrips,
        'yearExperience': value.yearExperience,
    };
}

