/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
} from './UserRoleEnum';

/**
 * 
 * @export
 * @interface DriverAddDTO
 */
export interface DriverAddDTO {
    /**
     * 
     * @type {string}
     * @memberof DriverAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DriverAddDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DriverAddDTO
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DriverAddDTO
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof DriverAddDTO
     */
    role?: UserRoleEnum;
}

/**
 * Check if a given object implements the DriverAddDTO interface.
 */
export function instanceOfDriverAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DriverAddDTOFromJSON(json: any): DriverAddDTO {
    return DriverAddDTOFromJSONTyped(json, false);
}

export function DriverAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriverAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'role': !exists(json, 'role') ? undefined : UserRoleEnumFromJSON(json['role']),
    };
}

export function DriverAddDTOToJSON(value?: DriverAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'password': value.password,
        'phoneNumber': value.phoneNumber,
        'role': UserRoleEnumToJSON(value.role),
    };
}

