/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DriverDTO } from './DriverDTO';
import {
    DriverDTOFromJSON,
    DriverDTOFromJSONTyped,
    DriverDTOToJSON,
} from './DriverDTO';

/**
 * 
 * @export
 * @interface DriverDTOPagedResponse
 */
export interface DriverDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof DriverDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof DriverDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof DriverDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<DriverDTO>}
     * @memberof DriverDTOPagedResponse
     */
    data?: Array<DriverDTO> | null;
}

/**
 * Check if a given object implements the DriverDTOPagedResponse interface.
 */
export function instanceOfDriverDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DriverDTOPagedResponseFromJSON(json: any): DriverDTOPagedResponse {
    return DriverDTOPagedResponseFromJSONTyped(json, false);
}

export function DriverDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriverDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(DriverDTOFromJSON)),
    };
}

export function DriverDTOPagedResponseToJSON(value?: DriverDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(DriverDTOToJSON)),
    };
}

