/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DriverUpdateDTO
 */
export interface DriverUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof DriverUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DriverUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DriverUpdateDTO
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DriverUpdateDTO
     */
    phoneNumber?: string | null;
}

/**
 * Check if a given object implements the DriverUpdateDTO interface.
 */
export function instanceOfDriverUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DriverUpdateDTOFromJSON(json: any): DriverUpdateDTO {
    return DriverUpdateDTOFromJSONTyped(json, false);
}

export function DriverUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriverUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
    };
}

export function DriverUpdateDTOToJSON(value?: DriverUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'password': value.password,
        'phoneNumber': value.phoneNumber,
    };
}

