/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RouteAddDTO
 */
export interface RouteAddDTO {
    /**
     * 
     * @type {string}
     * @memberof RouteAddDTO
     */
    routeName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteAddDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the RouteAddDTO interface.
 */
export function instanceOfRouteAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RouteAddDTOFromJSON(json: any): RouteAddDTO {
    return RouteAddDTOFromJSONTyped(json, false);
}

export function RouteAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'routeName': !exists(json, 'routeName') ? undefined : json['routeName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function RouteAddDTOToJSON(value?: RouteAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'routeName': value.routeName,
        'description': value.description,
    };
}

