/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Booking } from './Booking';
import {
    BookingFromJSON,
    BookingFromJSONTyped,
    BookingToJSON,
} from './Booking';
import type { CarRoute } from './CarRoute';
import {
    CarRouteFromJSON,
    CarRouteFromJSONTyped,
    CarRouteToJSON,
} from './CarRoute';

/**
 * 
 * @export
 * @interface Route
 */
export interface Route {
    /**
     * 
     * @type {string}
     * @memberof Route
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Route
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Route
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Route
     */
    routeName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Route
     */
    description?: string | null;
    /**
     * 
     * @type {Array<CarRoute>}
     * @memberof Route
     */
    carRoutes?: Array<CarRoute> | null;
    /**
     * 
     * @type {Array<Booking>}
     * @memberof Route
     */
    bookings?: Array<Booking> | null;
    /**
     * 
     * @type {string}
     * @memberof Route
     */
    routeLength?: string | null;
}

/**
 * Check if a given object implements the Route interface.
 */
export function instanceOfRoute(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RouteFromJSON(json: any): Route {
    return RouteFromJSONTyped(json, false);
}

export function RouteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Route {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'routeName': !exists(json, 'routeName') ? undefined : json['routeName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'carRoutes': !exists(json, 'carRoutes') ? undefined : (json['carRoutes'] === null ? null : (json['carRoutes'] as Array<any>).map(CarRouteFromJSON)),
        'bookings': !exists(json, 'bookings') ? undefined : (json['bookings'] === null ? null : (json['bookings'] as Array<any>).map(BookingFromJSON)),
    };
}

export function RouteToJSON(value?: Route | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'routeName': value.routeName,
        'description': value.description,
        'carRoutes': value.carRoutes === undefined ? undefined : (value.carRoutes === null ? null : (value.carRoutes as Array<any>).map(CarRouteToJSON)),
        'bookings': value.bookings === undefined ? undefined : (value.bookings === null ? null : (value.bookings as Array<any>).map(BookingToJSON)),
    };
}

