/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RouteUpdateDTO
 */
export interface RouteUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof RouteUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RouteUpdateDTO
     */
    routeName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteUpdateDTO
     */
    routeLength?: string | null;
}

/**
 * Check if a given object implements the RouteUpdateDTO interface.
 */
export function instanceOfRouteUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RouteUpdateDTOFromJSON(json: any): RouteUpdateDTO {
    return RouteUpdateDTOFromJSONTyped(json, false);
}

export function RouteUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'routeName': !exists(json, 'routeName') ? undefined : json['routeName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function RouteUpdateDTOToJSON(value?: RouteUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'routeName': value.routeName,
        'description': value.description,
    };
}

