version: "4.0"

services:
  mobylab-app-db:
    image: postgres:18-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: transportadmin
      POSTGRES_DB: transportdb
      POSTGRES_PASSWORD: admin
    volumes:
      - transport-app-db-vol:/var/lib/postgresql

volumes:
  transport-app-db-vol: