/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DriverInfoAddDTO,
  DriverInfoDTORequestResponse,
  DriverInfoUpdateDTO,
  RequestResponse,
} from '../models';
import {
    DriverInfoAddDTOFromJSON,
    DriverInfoAddDTOToJSON,
    DriverInfoDTORequestResponseFromJSON,
    DriverInfoDTORequestResponseToJSON,
    DriverInfoUpdateDTOFromJSON,
    DriverInfoUpdateDTOToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models';

export interface ApiDriverInfoAddPostRequest {
    driverInfoAddDTO?: DriverInfoAddDTO;
}

export interface ApiDriverInfoDeleteIdDeleteRequest {
    id: string;
}

export interface ApiDriverInfoGetByIdIdGetRequest {
    id: string;
}

export interface ApiDriverInfoUpdatePutRequest {
    driverInfoUpdateDTO?: DriverInfoUpdateDTO;
}

/**
 * 
 */
export class DriverInfoApi extends runtime.BaseAPI {

    /**
     */
    async apiDriverInfoAddPostRaw(requestParameters: ApiDriverInfoAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/DriverInfo/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DriverInfoAddDTOToJSON(requestParameters.driverInfoAddDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiDriverInfoAddPost(requestParameters: ApiDriverInfoAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiDriverInfoAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiDriverInfoDeleteIdDeleteRaw(requestParameters: ApiDriverInfoDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiDriverInfoDeleteIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/DriverInfo/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiDriverInfoDeleteIdDelete(requestParameters: ApiDriverInfoDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiDriverInfoDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiDriverInfoGetByIdIdGetRaw(requestParameters: ApiDriverInfoGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DriverInfoDTORequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiDriverInfoGetByIdIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/DriverInfo/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DriverInfoDTORequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiDriverInfoGetByIdIdGet(requestParameters: ApiDriverInfoGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DriverInfoDTORequestResponse> {
        const response = await this.apiDriverInfoGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiDriverInfoUpdatePutRaw(requestParameters: ApiDriverInfoUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/DriverInfo/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DriverInfoUpdateDTOToJSON(requestParameters.driverInfoUpdateDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiDriverInfoUpdatePut(requestParameters: ApiDriverInfoUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiDriverInfoUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
