/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DriverAddDTO,
  DriverDTOPagedResponseRequestResponse,
  DriverDTORequestResponse,
  DriverUpdateDTO,
  RequestResponse,
} from '../models';
import {
    DriverAddDTOFromJSON,
    DriverAddDTOToJSON,
    DriverDTOPagedResponseRequestResponseFromJSON,
    DriverDTOPagedResponseRequestResponseToJSON,
    DriverDTORequestResponseFromJSON,
    DriverDTORequestResponseToJSON,
    DriverUpdateDTOFromJSON,
    DriverUpdateDTOToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models';

export interface ApiDriverAddPostRequest {
    driverAddDTO?: DriverAddDTO;
}

export interface ApiDriverDeleteIdDeleteRequest {
    id: string;
}

export interface ApiDriverGetByIdIdGetRequest {
    id: string;
}

export interface ApiDriverGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiDriverUpdatePutRequest {
    driverUpdateDTO?: DriverUpdateDTO;
}

/**
 * 
 */
export class DriverApi extends runtime.BaseAPI {

    /**
     */
    async apiDriverAddPostRaw(requestParameters: ApiDriverAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Driver/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DriverAddDTOToJSON(requestParameters.driverAddDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiDriverAddPost(requestParameters: ApiDriverAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiDriverAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiDriverDeleteIdDeleteRaw(requestParameters: ApiDriverDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiDriverDeleteIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Driver/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiDriverDeleteIdDelete(requestParameters: ApiDriverDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiDriverDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiDriverGetByIdIdGetRaw(requestParameters: ApiDriverGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DriverDTORequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiDriverGetByIdIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Driver/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DriverDTORequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiDriverGetByIdIdGet(requestParameters: ApiDriverGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DriverDTORequestResponse> {
        const response = await this.apiDriverGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiDriverGetPageGetRaw(requestParameters: ApiDriverGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DriverDTOPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Driver/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DriverDTOPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiDriverGetPageGet(requestParameters: ApiDriverGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DriverDTOPagedResponseRequestResponse> {
        const response = await this.apiDriverGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiDriverUpdatePutRaw(requestParameters: ApiDriverUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Driver/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DriverUpdateDTOToJSON(requestParameters.driverUpdateDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiDriverUpdatePut(requestParameters: ApiDriverUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiDriverUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
