/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LocationDTOListRequestResponse,
} from '../models';
import {
    LocationDTOListRequestResponseFromJSON,
    LocationDTOListRequestResponseToJSON,
} from '../models';

export interface ApiLocationGetGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class LocationApi extends runtime.BaseAPI {

    /**
     */
    async apiLocationGetGetRaw(requestParameters: ApiLocationGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LocationDTOListRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Location/Get`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationDTOListRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLocationGetGet(requestParameters: ApiLocationGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LocationDTOListRequestResponse> {
        const response = await this.apiLocationGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
