/* tslint:disable */
/* eslint-disable */
/**
 * Transport App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RequestResponse,
  RouteAddDTO,
  RouteDTOPagedResponseRequestResponse,
  RouteDTORequestResponse,
  RouteUpdateDTO,
  StringRouteDTOListDictionaryRequestResponse,
} from '../models';
import {
    RequestResponseFromJSON,
    RequestResponseToJSON,
    RouteAddDTOFromJSON,
    RouteAddDTOToJSON,
    RouteDTOPagedResponseRequestResponseFromJSON,
    RouteDTOPagedResponseRequestResponseToJSON,
    RouteDTORequestResponseFromJSON,
    RouteDTORequestResponseToJSON,
    RouteUpdateDTOFromJSON,
    RouteUpdateDTOToJSON,
    StringRouteDTOListDictionaryRequestResponseFromJSON,
    StringRouteDTOListDictionaryRequestResponseToJSON,
} from '../models';

export interface ApiRouteAddPostRequest {
    routeAddDTO?: RouteAddDTO;
}

export interface ApiRouteDeleteIdDeleteRequest {
    id: string;
}

export interface ApiRouteGetByIdIdGetRequest {
    id: string;
}

export interface ApiRouteGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiRouteUpdatePutRequest {
    routeUpdateDTO?: RouteUpdateDTO;
}

/**
 * 
 */
export class RouteApi extends runtime.BaseAPI {

    /**
     */
    async apiRouteAddPostRaw(requestParameters: ApiRouteAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Route/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RouteAddDTOToJSON(requestParameters.routeAddDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRouteAddPost(requestParameters: ApiRouteAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiRouteAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRouteDeleteIdDeleteRaw(requestParameters: ApiRouteDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiRouteDeleteIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Route/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRouteDeleteIdDelete(requestParameters: ApiRouteDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiRouteDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRouteGetByIdIdGetRaw(requestParameters: ApiRouteGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RouteDTORequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiRouteGetByIdIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Route/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RouteDTORequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRouteGetByIdIdGet(requestParameters: ApiRouteGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RouteDTORequestResponse> {
        const response = await this.apiRouteGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRouteGetPageGetRaw(requestParameters: ApiRouteGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RouteDTOPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Route/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RouteDTOPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRouteGetPageGet(requestParameters: ApiRouteGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RouteDTOPagedResponseRequestResponse> {
        const response = await this.apiRouteGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRouteGetRoutesWithLocationsDictionaryGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringRouteDTOListDictionaryRequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Route/GetRoutesWithLocationsDictionary`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringRouteDTOListDictionaryRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRouteGetRoutesWithLocationsDictionaryGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringRouteDTOListDictionaryRequestResponse> {
        const response = await this.apiRouteGetRoutesWithLocationsDictionaryGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRouteUpdatePutRaw(requestParameters: ApiRouteUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Route/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RouteUpdateDTOToJSON(requestParameters.routeUpdateDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRouteUpdatePut(requestParameters: ApiRouteUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiRouteUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
